### ISSUE TITLE
v0.2.6 is broken

### ISSUE THREAD

**Issue by pavlin-policar** [conda-forge/fasttsne-feedstock#5]
Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org because:

All the packages with v0.2.6 are broken. I've recently updated the package to v0.2.7, which is fine, but in between, support for Python 3.5 was dropped, and there are no new builds. This means that I've got the working v0.2.7 version for Python 3.6 and the broken v0.2.6 version for Python 3.5.

**Comment by pavlin-policar** [comment]
Just to be extra clear, the packages that are broken are the following:
```
win-64/fasttsne-0.2.6-py36h452e1ab_0.tar.bz2
win-64/fasttsne-0.2.6-py35h452e1ab_0.tar.bz2
linux-64/fasttsne-0.2.6-py35h7eb728f_0.tar.bz2
linux-64/fasttsne-0.2.6-py36h7eb728f_0.tar.bz2
osx-64/fasttsne-0.2.6-py35h7eb728f_0.tar.bz2
osx-64/fasttsne-0.2.6-py36h7eb728f_0.tar.bz2
```

**Comment by ocefpaf** [comment]
Done! Can you check if I got it right?

https://anaconda.org/conda-forge/fasttsne/files?version=0.2.6

**Comment by pavlin-policar** [comment]
Yes, you got it all. Thanks!

**Comment by ocefpaf** [comment]
BTW, sometimes we miss the pings on individual feedstocks. Feel free to post request like this one on our gitter channel too.

**Comment by pavlin-policar** [comment]
Oh, thanks for the heads up.
